[build]
  cmd = "go build -o ./bin/server ./cmd/server"
  entrypoint = ["./bin/server"]
  full_bin = "ADDR=:8080 ./bin/server"
  exclude_dir = ["tmp", "vendor", "frontend"]
  delay = 100

[misc]
  clean_on_exit = true
