apiVersion: v1
kind: Service
metadata:
  name: letsagree-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsagree.labels" . | nindent 4 }}
spec:
  selector:
    app: letsagree-backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
