apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "letsagree.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.frontend.ingress.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.frontend.ingress.host }}
      secretName: {{ .Values.frontend.ingress.host }}-tls
