apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "letsagree.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "letsagree.frontend.image" . }}
          args:
            - --addr=:{{ .Values.frontend.port }}
            - --backend=http://letsagree-backend:{{ .Values.backend.port }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              path: /about
              port: http
