postgres:
  instances: 1
  image: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 1Gi
  nodePort: 30432
  database:
    name: letsagree
    owner: app

backend:
  image: ghcr.io/zon/letsagree-backend
  port: 8080
  replicas: 1
  ingress:
    host: api.letsagree.win
    clusterIssuer: lets-encrypt
    ingressClassName: public

frontend:
  image: ghcr.io/zon/letsagree-frontend
  port: 3000
  replicas: 1
  ingress:
    host: letsagree.win
    clusterIssuer: lets-encrypt
    ingressClassName: public
